. ~/.aliases
putMimeType aac audio/aac
putMimeType ai application/postscript
putMimeType avi video/avi
putMimeType flac audio/flac
putMimeType bash text/plain
putMimeType html text/html
putMimeType woff application/font-woff
putMimeType svg image/svg+xml
putMimeType js application/javascript
putMimeType docx application/vnd.openxmlformats-officedocument.wordprocessingml.document
putMimeType jpeg image/jpeg
putMimeType tar application/x-tar
putMimeType asc text/plain
putMimeType ps application/postscript
putMimeType webp image/webp
putMimeType pdf application/pdf
putMimeType txt text/plain
putMimeType opus audio/ogg
putMimeType gif image/gif
putMimeType png image/png
putMimeType vcf text/vcard
putMimeType css text/css
putMimeType mp3 audio/mpeg
putMimeType mpg video/mpeg
putMimeType mpeg video/mpeg
putMimeType mkv video/mp4
putMimeType md text/x-markdown
putMimeType tif image/tiff
putMimeType cbz application/x-cbz
putMimeType otf font/opentype
putMimeType sh text/plain
putMimeType webm video/webm
putMimeType flv video/x-flv
putMimeType cbr application/x-cbr
putMimeType zip application/zip
putMimeType tiff image/tiff
putMimeType wmv video/x-ms-wmv
putMimeType xlsx application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
putMimeType jpg image/jpeg
putMimeType ttf font/ttf
putMimeType json application/json
putMimeType htm text/html
putMimeType mp4 video/mp4
putMimeType epub application/epub+zip
putMimeType coffee text/x-coffeescript
putMimeType m4v video/mp4
putMimeType wma audio/x-ms-wma
